services:
  test:
    build:
      context: .
      dockerfile: bonsai.Dockerfile
    volumes:
      - ./bonsai:/app/bonsai
      - ./tests:/app/tests
    command: uv run taskipy test
  build:
    build: .
    volumes:
      - ./bonsai:/app/bonsai
    command: uv run taskipy build

  build-riscv-tests:
    build:
      context: .
      dockerfile: riscv-toolchain.Dockerfile
    volumes:
      - ./misc:/app/.misc
      - ./riscv-tests:/app/riscv-tests
    command: bash -c "cd /app/riscv-tests && chmod +x build-riscv-tests.sh && ./build-riscv-tests.sh"
