services:
  test:
    build:
      context: .
      dockerfile: bonsai.Dockerfile
    volumes:
      - ./bonsai:/app/bonsai
      - ./tests:/app/tests
    command: uv run taskipy test
  build:
    build: .
    volumes:
      - ./bonsai:/app/bonsai
    command: uv run taskipy build

  build-riscv-tests:
    build:
      context: .
      dockerfile: riscv-toolchain.Dockerfile
    volumes:
      - ./misc:/app/misc:ro
      - ./riscv-tests:/app/riscv-tests:rw
    command: bash -c "cd /app/riscv-tests && chmod +x /app/misc/build-riscv-tests.sh && /app/misc/build-riscv-tests.sh"
