services:
  test:
    build: .
    volumes:
      - ./bonsai:/app/bonsai
      - ./tests:/app/tests
    command: uv run taskipy test
  build:
    build: .
    volumes:
      - ./bonsai:/app/bonsai
    command: uv run taskipy build
