[project]
name = "bonsai"
version = "0.1.0"
description = "toy risc-v processor"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "amaranth-boards",
    "amaranth[builtin-yosys]>=0.5.3",
    "asyncio>=3.4.3",
]

[dependency-groups]
dev = [
    "jupyterlab>=4.3.1",
    "pytest-mock>=3.14.0",
    "pytest>=8.3.3",
    "ruff>=0.7.4",
    "pytest-cov>=6.0.0",
    "pytest-html>=4.1.1",
    "amaranth-yosys>=0.40.0.0.post100",
]

[tool.uv.sources]
amaranth-boards = { git = "https://github.com/amaranth-lang/amaranth-boards.git" }
