[project]
name = "rusk"
version = "0.1.0"
description = "toy risc-v processor"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "amaranth-boards",
    "amaranth[builtin-yosys]>=0.5.3",
    "asyncio>=3.4.3",
]

[dependency-groups]
dev = ["jupyterlab>=4.3.1", "ruff>=0.7.4"]

[tool.uv.sources]
amaranth-boards = { git = "https://github.com/amaranth-lang/amaranth-boards.git" }
