from typing import List
from bonsai.inst import InstDef, InstFormat, Opcode

# RV32I Base Integer Instructions

reg_reg_insts: List[InstDef] = [
    InstDef(
        inst="add",
        name="ADD",
        fmt=InstFormat.R,
        opcode=Opcode.OP,
        funct3=0b000,
        funct7=0b0000000,
        desc="rd = rs1 + rs2",
    ),
    InstDef(
        inst="sub",
        name="SUB",
        fmt=InstFormat.R,
        opcode=Opcode.OP,
        funct3=0b000,
        funct7=0b0100000,
        desc="rd = rs1 - rs2",
    ),
    InstDef(
        inst="sll",
        name="Shift Left Logical",
        fmt=InstFormat.R,
        opcode=Opcode.OP,
        funct3=0b001,
        funct7=0b0000000,
        desc="rd = rs1 << rs2",
    ),
    InstDef(
        inst="slt",
        name="Set Less Than",
        fmt=InstFormat.R,
        opcode=Opcode.OP,
        funct3=0b010,
        funct7=None,
        desc="rd = rs1 < rs2 ? 1 : 0",
    ),
    InstDef(
        inst="sltu",
        name="Set Less Than Unsigned",
        fmt=InstFormat.R,
        opcode=Opcode.OP,
        funct3=0b011,
        funct7=None,
        desc="rd = rs1 < rs2 ? 1 : 0",
    ),
    InstDef(
        inst="xor",
        name="XOR",
        fmt=InstFormat.R,
        opcode=Opcode.OP,
        funct3=0b100,
        funct7=0b0000000,
        desc="rd = rs1 ^ rs2",
    ),
    InstDef(
        inst="srl",
        name="Shift Right Logical",
        fmt=InstFormat.R,
        opcode=Opcode.OP,
        funct3=0b101,
        funct7=0b0000000,
        desc="rd = rs1 >> rs2",
    ),
    InstDef(
        inst="sra",
        name="Shift Right Arithmetic",
        fmt=InstFormat.R,
        opcode=Opcode.OP,
        funct3=0b101,
        funct7=0b0100000,
        desc="rd = rs1 >> rs2",
    ),
    InstDef(
        inst="or",
        name="OR",
        fmt=InstFormat.R,
        opcode=Opcode.OP,
        funct3=0b110,
        funct7=0b0000000,
        desc="rd = rs1 | rs2",
    ),
    InstDef(
        inst="and",
        name="AND",
        fmt=InstFormat.R,
        opcode=Opcode.OP,
        funct3=0b111,
        funct7=0b0000000,
        desc="rd = rs1 & rs2",
    ),
]
