# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Pytest

on:
  push:
  pull_request:

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Cache python env
        id: cache-python-env
        uses: actions/cache@v4
        with:
          path: "**/.venv"
          key: python-${{ hashFiles('**/.venv') }}

      - name: Set up Python
        if: ${{ steps.cache-python-env.outputs.cache-hit != 'true' }}
        run: uv python install

      - name: Install the project
        if: ${{ steps.cache-python-env.outputs.cache-hit != 'true' }}
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest -v -rfs
